apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: crowdsec-bouncer
  namespace: traefik
spec:
  plugin:
    crowdsec-bouncer:
      enabled: true
      crowdsecLapiKeyFile: /etc/crowdsec/key
      crowdsecLapiHost: crowdsec-service.crowdsec.svc.cluster.local:8080
