apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`torrent.miquella.dev`)
      kind: Rule
      services:
        - name: qbittorrent
          port: {{ .Values.port }}
  tls:
    certResolver: cloudflare
