apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Thewolf2068/k3s-test
    targetRevision: HEAD
    path: charts/my-services     # <--- CHANGED: Points to the folder with Chart.yaml
    helm:
      valueFiles:
        - values.yaml            # <--- ADDED: Tells ArgoCD to inject these variables
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
