apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media
  namespace: media
spec:
  project: default
  source:
    repoURL: 'https://github.com/thewolf2068/k3s-test.git'
    targetRevision: HEAD
    path: charts/media
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
