apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: "26.1.0"
    helm:
      values: |
        globalArguments:
          - "--global.sendanonymoususage=false"
        additionalArguments:
          - "--experimental.plugins.crowdsec-bouncer.moduleName=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
          - "--experimental.plugins.crowdsec-bouncer.version=v1.3.5"
          - "--providers.kubernetesCRD.allowCrossNamespaceReferences=true"
        ports:
          web:
            port: 8000
            exposedPort: 80
            redirectTo:
              port: websecure
          websecure:
            port: 8443
            exposedPort: 443
        certResolvers:
          cloudflare:
            email: "malenia@miquella.dev"
            dnsChallenge:
              provider: cloudflare
              resolvers:
                - "1.1.1.1:53"
                - "8.8.8.8:53"
            storage: /data/acme.json
        persistence:
          enabled: true
          size: 128Mi
        env:
          - name: CF_DNS_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-token
                key: token
        ingressRoute:
          dashboard:
            enabled: false
        logs:
          access:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
