apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media
spec:
  selector:                   
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:                 
        app: prowlarr
      annotations:
        pre.hook.backup.velero.io/container: prowlarr
        pre.hook.backup.velero.io/command: '["/bin/sh", "-c", "kill -STOP $(pidof prowlarr || echo 1)"]'
        post.hook.backup.velero.io/container: prowlarr
        post.hook.backup.velero.io/command: '["/bin/sh", "-c", "kill -CONT $(pidof prowlarr || echo 1)"]'
    spec:
      securityContext:
        runAsUser: {{ .Values.global.securityContext.runAsUser }}
        runAsGroup: {{ .Values.global.securityContext.runAsGroup }}
        fsGroup: {{ .Values.global.securityContext.runAsGroup }}
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: prowlarr
          image: ghcr.io/home-operations/prowlarr:{{ .Values.imageTag }}
          ports:
            - containerPort: {{ .Values.port }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
      volumes:
        - name: tmp
          emptyDir: {}
        - name: media
          hostPath: 
            path: /media
            type: Directory
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config-pvc
