apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.subdomain }}.miquella.dev`)
      kind: Rule
      services:
        - name: prowlarr
          port: {{ .Values.port }}
  tls:
    certResolver: cloudflare
