apiVersion: v2
name: my-services
description: A Helm umbrella chart for my home lab
version: 0.1.0

dependencies:
  - name: jellyfin
    version: "0.1.0"
    repository: "file://./charts/jellyfin"
    condition: jellyfin.enabled


  - name: navidrome
    version: "0.1.0"
    repository: "file://./charts/navidrome"
    condition: navidrome.enabled

  - name: qbittorrent
    version: "0.1.0"
    repository: "file://./charts/qbittorrent"
    condition: qbittorrent.enabled
