global:
  domain: "miquella.dev"
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000

jellyfin:
  enabled: true
  imageTag: "10.10.7"
  port: 8096

navidrome:
  enabled: true
  imageTag: "0.61.2"
  port: "4533"

qbittorrent:
  enabled: true
  imageTag: "rolling@sha256:bb82ad6668f8eda1d0fcce6c1341498bfa879155bb1295cd9d314a2c35c07a01"
  port: "8080"
