- name: Create ArgoCD namespace
  ansible.builtin.command:
    cmd: kubectl create namespace argocd
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  become: true
  register: ns_result
  failed_when:
    - ns_result.rc != 0
    - '"already exists" not in ns_result.stderr'

- name: Install ArgoCD
  ansible.builtin.command:
    cmd: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.13.0/manifests/install.yaml
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  become: true
