apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: navidrome
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`music.miquella.dev`)
      kind: Rule
      services:
        - name: navidrome
          port: {{ .Values.port }}
  tls:
    certResolver: cloudflare
