---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: navidrome-secrets
#  namespace: media
spec:
  encryptedData:
    lastfm-api-key: AgBQn+O2kvviORXo0qYgWb3nhcVe4UXt7qeCk6tk+Q8B1joqUbXue5Ns8ZkcUKg9ZbrPpoJ4JPMuJTYbwbh5bCaL6BfLpuKdImxeTgs6yLc10vYUM29UxOWGRv70pwJ7H1pSAN9hIrmuuwGhrFmX4mvP8Le7xG3swdRCa17unnRell4nE+17UyADoEY6nMp8BM/KEMxoe7QgNDA1w/ZdK21xFo80hVduNHXomdSenuFnoFjVqEwoKhjHRhEAVr/PAjJnEnrGySxSf/geRLg1kuCPbAARJIlgq4awAx5nUefX3LGy3aeTrSviomo4vKOmrSvayaOHmBa8Bmn7SbrzVD26z0QTtAaRjbVrZC/400+EauKgepnvIOjEtPx0N7l0AO03VjQUuWy0l+n/5P5rkfFOWZlvNBbef1EtwrYbrSWx2RNNHPSg+X8gQRXlIXgfovuASATu8Hrk1SD/jnLw3TVQq/sVEnUwJrav1mdiX+XSYyqxnvR94kujbTo01wvc4oeRyBubbNVg/ZVy3DLDXmsEqku6w2nLM33gtoC8FCWfvD0O64Pzi9AN8Ajl0sC57BhXi0SwjuIT8LhwcPMNL9Uc0r8r8S0bI7iwT6IgXx/x2TV4E27aRuIVO5uEnECj5s6C4CJHrSojY1rysOZBq2ZzPRAmYh5hUHuL/mlPoLT/xAZAEtByJ2XqpeDydJ5XGsVSApPf3zSFTROdr8WfxdwhILpuVgdXTbkKVxCTxZwVdg==
    lastfm-secret: AgC7r3y6Lyeg3xXGk/xa2HQ6VBq1F7C3UMAlznuIlfQ3qeJwnllbvFQInTMyOobuZZE09krRepyodtJvLD5sR8FmcEw/BVKCeX6LH+sKkVZM6KCgYBirnRMeuini/WNMry2Ivxd4pFBjKrVUvdlizDiLMm04uYB+qHV/VOvIrMkn4Nu1c9vG3lVgoLmOOh/CkTrHCcF/3UlZMOWGJDIc8suWkZP0t2IOzFaCPkBCePEL4I7F95H3oVMY76YCqKd0uVTDMCJa8M4LqBwuwI5Rr1J2FUDWvuQdyp05E7Sl3xOSiYP265dFNtoe3VYHiWVqhyQNuHz6IPNrlZeHwLnPpHGCfk0/kMn+JRaOXTzlXQrQzdHaXnPWeDeFEWXzhCR94nyDZk6bhGGZsKnZYyLbEwtpiwjjhqaIKtJ4IUh2znlYe+bvN6kOtCvk2QCBeKKGKwLgU4J3PRS6MR/zebDgK7rmufZA8RHFSs64uAFEgKfUe8oHTjCfXzRjLCZWdyHWm4jcJCOVUakcdxloKC5C+rycO89xlaoWnShy0hwTjOs0pzhaYUkt10eBJh/nt+CzyTYibJ9CfJZVqidh9bRvaZfgu+NQL+bfXabGCM8VUxKJXl/ZntXxqJOqA8mKUE6N0TFa84iz1jzRO3mXrR4ckaQKStfACmK10Ze5daAAaB6H6W7y/pHrutKz2qmcrizivNLKmJZ4npYcAFTN9UvJKJfL6jrXDOGG7nZU9IwnlkAaAVj1h7KI
  template:
    metadata:
      name: navidrome-secrets
#      namespace: media
