apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  namespace: navidrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      securityContext:
        runAsUser: {{ .Values.global.securityContext.runAsUser }}
        runAsGroup: {{ .Values.global.securityContext.runAsGroup }}
      containers:
        - name: navidrome
          image: deluan/navidrome:{{ .Values.imageTag }}
          ports:
            - containerPort: {{ .Values.port }}
          volumeMounts:
            - name: data
              mountPath: /data
            - name: music
              mountPath: /music
          env:
            - name: ND_LASTFM_APIKEY
              valueFrom:
                secretKeyRef:
                  name: navidrome-secrets
                  key: lastfm-api-key
            - name: ND_LASTFM_SECRET
              valueFrom:
                secretKeyRef:
                  name: navidrome-secrets
                  key: lastfm-api-secret
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: navidrome-data-pvc
        - name: music
          hostPath:
            path: /media/music
