---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: navidrome-secrets
  namespace: navidrome
spec:
  encryptedData:
    lastfm-api-key: AgCkCvM3hZR/RpQFSnAmZTdNOBimtcDV5LbYeqyF9rw5ZIJL7Jp5Enc7Z9fyHrtKX+/+2Ai/66ILRFc3shJed09eQ9ZMsmZPNpmTOwblNYoLT3omiVYsNbnBknlDTFA/GDaY5msC75yGsftAMQz9dpBIZg3CR4uwDtJq5bvDZM3DHfsfekULLCpzZNzjB8RhGXAoq0pdWhKxg3dUUUS8L7UFtuSEXDQLhAKknae0WOv6zUqIVxbJNRFTz1uh6nscK200K4VX6d9a/q/+Qke9jK/715JD4W3gXP+yf+TNHttdgcA0Wk1w52vgu4Cym20zLgsv3UgLsVVM1Tb8yahltj048rUAf7utMfnCXNra4cOfLXDgCEQ5OlGRC0w3AMOUsaV4ksY75l4GM8mcyl4klWSnpTyZN3AtcS2kC97g2XL7B73+sEocjgqwxD5OXXZYObjFBwuZH4Z9gTM/29vSKdFFy49ML9bEhcfQtUxd1E5g0YhrrY7kbLQJyPZpczZnLGuh29bZqs/8hjhKgMKXQJQNbnSxUcGwzhUf/D7DNSYeFeVSEL1DcQ+IpOsvozyUE8fierhKIfVMj8C3hcS7UxLVsIfdO5crl9VUKDha0XamANDZfQnywnHl2xOnB6z8wvChvaTrVxd0Kqbw1jtdwODi1xEWtOdFfwQHzK0PoypAIkhIC2VMNk1nIeWJqLOA+tpypnoDBClx/JYjMaLvFIjyIsp+3EPjbXK5zvalM7+yAA==
    lastfm-secret: AgAGqrWVXr/D7e+/lwgC67z+7aap4w95LwtLzRKWWZSbfCP1Fuv/nxxAc8LVGXoeYykXZLW3hyfrDdeJ3IVXSv5uiXPpssLcNpd/6Sm/PCxP946cZ/QWVcfM07aGNdpD8jKTENhvEiuWR452fflqppmo30VRHu2qauVay643EIkuH1ABd2fG1L7kFLOE1ZsaiBs3iYUjcC9hBSS5qt3JriYST0Ci0dIEfxqDjwb0/RYGoyoS+xuM/iuAD4nyjh9PWJROpTJ3H//xfX+HebNafCtCBTyZj1fct/hAHEcaqid/yiZqTwEzZgRwuGln0IlagBEWVMRJwJPgN0/llEhNUwMMAW9gr19wqhVNUpkbWb8Sa3fBbKrP+eggbTA057AuYvPddqZC6gNz5p0buXYxMHJ6QhuN6z4Teha3t/YvsAaENyahWKrZZXZ7I4KoJYs03wLrVDFtlVmWcvZnJI3Sfape/b+Hk2GFOeRBk5DnK89TNIRW7gMUNIUUpAwU+DY/gm3cNQHliqvG3SEvLkdEPa64u7ZckxuBA9PeEH3oUiaXgeD2AUWqLRY8QnyGCJ9KUaGiHyuTh7FiovurhBL6X+mDepTvBnluiep9eUdrDuZ2tJVpsnBAVhrOaju3O9mKCfmfyfW/piPjVmkDmlhUr7lNzx5lGOmUCL2sgo/y9gkDvSZ9WJSOmd5WakgqYlZkI+bee25MqNgJixNozFLS69aVxaTVBIAGuCi2qPhyX1cXOtPyGqV5
  template:
    metadata:
      name: navidrome-secrets
      namespace: navidrome
